branches:
    only:
        - master
os:
    - linux
services:
    - docker
language: java
sudo: true
jdk:
    - openjdk8
cache:
    directories:
        - $HOME/.m2
env:
    global:
        - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
        - SPRING_JPA_SHOW_SQL=false
        - MAVEN_USER_HOME=$HOME/.m2/repository/
before_install:
    - java -version
    - chmod +x mvnw
#install:
#  - . install
script:
    - chmod +x mvnw
    - ./mvnw -ntp clean verify
    - ./mvnw -ntp sonar:sonar -Dsonar.login=$SONAR_TOKEN
#after_success:
#  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
notifications:
    webhooks:
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: false     # default: false
